### ISSUE TITLE
Move some (all?) "suggested" packages to "depends"

### ISSUE THREAD

**Issue by geneorama** [jfisher-usgs/RSurvey#1]
I would suggest moving the "suggested" packages to "depends", since you need those packages to load the library without issue.
![image](https://cloud.githubusercontent.com/assets/1392068/6113428/dd493cea-b05c-11e4-9b01-8f6770e5a1ff.png)

**Comment by geneorama** [comment]
(or you may want to make the dialogue box more obvious that the missing packages are not necessary)

**Comment by jfisher-usgs** [comment]
Thanks for the suggestion. I'm trying to keep the number of dependent packages to a minimum so I opted for revising the dialog box.
![managepackages](https://cloud.githubusercontent.com/assets/681778/6308283/6597eb90-b900-11e4-84d8-b1fc4d65d649.png)
