### ISSUE TITLE
Vignette / blog link

### ISSUE THREAD

**Issue by geneorama** [jfisher-usgs/RSurvey#2]
I would suggest prominently displaying putting a link to the [github.io] (http://jfisher-usgs.github.io/) page into the README.md.  It would be extremely helpful for getting started.  (I would actually link to specific blog posts rather than to the page in general).

**Comment by jfisher-usgs** [comment]
I'm going to hold off on this because the blog [post](http://jfisher-usgs.github.io/r/2012/06/01/color-tools/ ) (which has been updated) is specific to color palette selection. As soon as I can find the time, I'd like to create a vignette describing each of the package GUI's.
